# Test several settings (Agda version, heap size)

name: Matrix

on:
  push:
    branches:
      - master
      - ci-*
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  STDLIB_VERSION: '2.0'
  MAIN: Everything.agda

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        agda: [2.6.4.1] #, 2.6.4]
        maxheap: [5G, 6G, 8G, 10G]
          # With 4.5G we still ran out of heap:
          # https://github.com/graded-type-theory/graded-type-theory/issues/23

    steps:

      # Checkout to $HOME empties $HOME so we have to do it before we put stuff there.
      - uses: actions/checkout@v4

      - name: Setup Agda
        uses: wenkokke/setup-agda@latest
        with:
          agda-version: ${{ matrix.agda }}
          agda-stdlib-version: ${{ env.STDLIB_VERSION }}

      - name: Run Agda
        run: agda "${{ env.MAIN }}" +RTS -M${{ matrix.maxheap }} -RTS
